### ISSUE TITLE
Breakage with HA 0.93

### ISSUE THREAD

**Issue by nfrntrd** [groupwhere/homeassistant-tivo#12]
New error when upgrading from 0.92 to 0.93

2019-05-17 20:52:35 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/home/ha/homeassistant/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 225, in async_update_ha_state
    self._async_write_ha_state()
  File "/home/ha/homeassistant/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 255, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/home/ha/homeassistant/lib/python3.6/site-packages/homeassistant/components/media_player/__init__.py", line 762, in state_attributes
    in ATTR_TO_PROPERTY if getattr(self, attr) is not None
  File "/home/ha/homeassistant/lib/python3.6/site-packages/homeassistant/components/media_player/__init__.py", line 762, in <dictcomp>
    in ATTR_TO_PROPERTY if getattr(self, attr) is not None
  File "/home/ha/.homeassistant/custom_components/tivo/media_player.py", line 352, in media_content_id
    return self._current["status"]
KeyError: 'status'

**Comment by jcollas** [comment]
This quick hack fixes this issue

diff --git a/tivo/media_player.py b/tivo/media_player.py
index 4b5d508..4179c56 100644
--- a/tivo/media_player.py
+++ b/tivo/media_player.py
@@ -349,7 +349,7 @@ class TivoDevice(MediaPlayerDevice):
         """Return the content ID of current playing media."""
         if self._is_standby:
             return None
-        return self._current["status"]
+        return self._current.get("status") or "STANDBY"
 
     @property
     def media_duration(self):
@@ -419,7 +419,7 @@ class TivoDevice(MediaPlayerDevice):
             return None
 
         return "{} ({})".format(
-            self._current['status'], self._current['channel'])
+            self._current.get('status') or 'STANDBY', self._current.get('channel') or "")
 
     @property
     def turn_on(self):

**Comment by RFC1920** [comment]
Sorry, can you reformat that, please?  Looks all wrong here.

**Comment by jcollas** [comment]
Yeah, that didn't turn out the way I wanted.

[homeassistant-tivo.txt](https://github.com/groupwhere/homeassistant-tivo/files/3268654/homeassistant-tivo.txt)

**Comment by jcollas** [comment]
a commit has been done which adds zeroconf configuration, and fixes the issues reported.

**Comment by jcollas** [comment]
I believe 0.3.0 fixes this
