### ISSUE TITLE
problem in Hassio 0.96.5

### ISSUE THREAD

**Issue by RPaulsson** [groupwhere/homeassistant-tivo#21]
Get this error when restarting Hassio.. 

2019-07-26 18:50:13 ERROR (MainThread) [homeassistant.components.media_player] Error while setting up platform tivo
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 126, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/tivo/media_player.py", line 113, in setup_platform
    tivos.append(TivoDevice(*host))
TypeError: __init__() takes 7 positional arguments but 8 were given

Thankyou for your good work..

**Comment by jcollas** [comment]
Can you share your configuration?  Also, are you using the latest version (0.4.0)?

**Comment by groupwhere** [comment]
Juan, I am looking at something.  It appears that if you do manually configure a device, hosts is still filled with zapuser/zappass instead of client.  I think I have a working version but am still testing.

**Comment by groupwhere** [comment]
Committed the minor fix for that.  However, in my case, the zap2client is not working.  No error but maybe my creds aren't working anymore.
