### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by jayheavner** [groupwhere/homeassistant-tivo#23]
I'm getting errors in my home assistant log and it looks like the last code push was quite some time ago.

**Comment by jcollas** [comment]
Jay,

I think it’s abandoned.  Miles is no longer using TiVos, and I was the last to work on it.  If you send me a log, I’m happy to take a look.

Juan

**Comment by jayheavner** [comment]
Thanks!

Here's what I'm seeing in my logs.

```
home-assistant    | 2020-11-18T22:43:21.839322546Z 2020-11-18 17:43:21 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved
home-assistant    | 2020-11-18T22:43:21.839365837Z Traceback (most recent call last):
home-assistant    | 2020-11-18T22:43:21.839381449Z   File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
home-assistant    | 2020-11-18T22:43:21.839394530Z     result = self.fn(*self.args, **self.kwargs)
home-assistant    | 2020-11-18T22:43:21.839406421Z   File "/config/custom_components/tivo/media_player.py", line 119, in update_status
home-assistant    | 2020-11-18T22:43:21.839418792Z     tivo.get_status()
home-assistant    | 2020-11-18T22:43:21.839429874Z   File "/config/custom_components/tivo/media_player.py", line 256, in get_status
home-assistant    | 2020-11-18T22:43:21.839441773Z     data = self.send_code('','')
home-assistant    | 2020-11-18T22:43:21.839452704Z   File "/config/custom_components/tivo/media_player.py", line 321, in send_code
home-assistant    | 2020-11-18T22:43:21.839463860Z     self.connect(self._host, self._port)
home-assistant    | 2020-11-18T22:43:21.839475671Z   File "/config/custom_components/tivo/media_player.py", line 244, in connect
home-assistant    | 2020-11-18T22:43:21.839487787Z     self.sock.connect((host, port))
home-assistant    | 2020-11-18T22:43:21.839498781Z socket.timeout: timed out

```

**Comment by RFC1920** [comment]
Dead for me since my tivo is now offline.  Perhaps Juan?

**Comment by jcollas** [comment]
Jay,

Can you try the version here

	https://github.com/jcollas/homeassistant-tivo

It’s some bug fixes that I didn’t move back into Miles’ repo.

Juan

**Comment by jayheavner** [comment]
I installed it. I got some Zap2It errors but I haven't dug deeply. I'm having problems with my hardware so I'm migrating everything and then I'll look into this more closely.
