### ISSUE TITLE
TiVo Component Not Loaded

### ISSUE THREAD

**Issue by Shugabuga** [groupwhere/homeassistant-tivo#5]
I just installed the `tivo` component and I cannot see any TiVo devices due to an error [around line 345](https://github.com/groupwhere/homeassistant-tivo/blob/1434efc1098063e44a5676ad78b6bd399810001c/tivo.py#L339-L345). What exactly is causing this, and is it a bug with the component or user error?

HomeAssistant installed through hass.io and trying to access a TiVo Bolt on the TiVo redesign (the telnet API still is present).

Excerpt from `configuration.yaml`
```yaml
media_player:
  - platform: tivo
    host: 192.168.1.3
    name: "Living Room TiVo"
    port: 31339
    device: 0
    debug: 1
```

Logs:
```bash
2018-05-07 21:46:03 WARNING (SyncWorker_0) [custom_components.media_player.tivo] update_status: <Entity Living Room TiVo: playing>
2018-05-07 21:46:03 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 222, in async_update_ha_state
    attr = self.state_attributes or {}
  File "/usr/lib/python3.6/site-packages/homeassistant/components/media_player/__init__.py", line 876, in state_attributes
    in ATTR_TO_PROPERTY if getattr(self, attr) is not None
  File "/usr/lib/python3.6/site-packages/homeassistant/components/media_player/__init__.py", line 876, in <dictcomp>
    in ATTR_TO_PROPERTY if getattr(self, attr) is not None
  File "/config/custom_components/media_player/tivo.py", line 345, in media_content_id
    return self._current["status"]
KeyError: 'status'
2018-05-07 21:46:03 WARNING (SyncWorker_0) [custom_components.media_player.tivo] get_status called...
2018-05-07 21:46:03 INFO (MainThread) [homeassistant.core] Bus:Handling <Event system_log_event[L]: timestamp=1525743963.373554, level=WARNING, message=update_status: <Entity Living Room TiVo: playing>, exception=, source=custom_components/media_player/tivo.py>
2018-05-07 21:46:03 WARNING (SyncWorker_0) [custom_components.media_player.tivo] Connecting to device...
2018-05-07 21:46:03 INFO (MainThread) [homeassistant.core] Bus:Handling <Event system_log_event[L]: timestamp=1525743963.3862197, level=ERROR, message=Error doing job: Task exception was never retrieved, exception=Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 222, in async_update_ha_state
    attr = self.state_attributes or {}
  File "/usr/lib/python3.6/site-packages/homeassistant/components/media_player/__init__.py", line 876, in state_attributes
    in ATTR_TO_PROPERTY if getattr(self, attr) is not None
  File "/usr/lib/python3.6/site-packages/homeassistant/components/media_player/__init__.py", line 876, in <dictcomp>
    in ATTR_TO_PROPERTY if getattr(self, attr) is not None
  File "/config/custom_components/media_player/tivo.py", line 345, in media_content_id
    return self._current["status"]
KeyError: 'status'
, source=custom_components/media_player/tivo.py>
2018-05-07 21:46:03 INFO (MainThread) [homeassistant.core] Bus:Handling <Event system_log_event[L]: timestamp=1525743963.4231317, level=WARNING, message=get_status called..., exception=, source=custom_components/media_player/tivo.py>
2018-05-07 21:46:03 INFO (MainThread) [homeassistant.core] Bus:Handling <Event system_log_event[L]: timestamp=1525743963.4584684, level=WARNING, message=Connecting to device..., exception=, source=custom_components/media_player/tivo.py>
2018-05-07 21:46:03 WARNING (SyncWorker_0) [custom_components.media_player.tivo] Sending request: ''
2018-05-07 21:46:03 INFO (MainThread) [homeassistant.core] Bus:Handling <Event system_log_event[L]: timestamp=1525743963.4956412, level=WARNING, message=Sending request: '', exception=, source=custom_components/media_player/tivo.py>
```

**Comment by groupwhere** [comment]
Essentially, it failed to connect and raises the empty exception as a result.  Is there any way you can test connecting to the device via telnet (windows or Linux)?

**Comment by Shugabuga** [comment]
Okay, it started to load. That must have been it, and it might have just taken some time of hass.io being online with the extension in order to work.

Now for specifying additional devices (like TiVo Minis): do we have to increment the `device` value or does the below suffice?

`configuration.yaml`:
```bash
media_player:
  - platform: tivo
    host: 192.168.1.3
    name: "Living Room TiVo"
    port: 31339
    device: 0
    debug: 1
    zapuser: zap@shuga.co
    zappass: !secret zap
  - platform: tivo
    host: 192.168.1.75
    name: "Kitchen TiVo"
    port: 31339
    device: 0
    debug: 1
    zapuser: zap@shuga.co
    zappass: !secret zap
```

**Comment by groupwhere** [comment]
I would think so.  I haven't had the luxury since I only have the one device.

**Comment by Shugabuga** [comment]
I just tested it, and it seemingly doesn't matter what `device` is set to.

I have all of mine set to `0` without any issues so far.
