### ISSUE TITLE
I'm logging this error

### ISSUE THREAD

**Issue by jayheavner** [groupwhere/homeassistant-tivo#7]
2018-08-03 11:41:51 ERROR (MainThread) [homeassistant.components.media_player] Error while setting up platform tivo
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 129, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/media_player/tivo.py", line 108, in setup_platform
    tivos.append(TivoDevice(*host))
  File "/config/custom_components/media_player/tivo.py", line 158, in __init__
    self.zapget_data()
  File "/config/custom_components/media_player/tivo.py", line 568, in zapget_data
    self.zapget_titles()
  File "/config/custom_components/media_player/tivo.py", line 592, in zapget_titles
    tmp = _ev[0]
IndexError: list index out of range

Also, I've configured 3 tivos. I haven't looked that the code but is it making 3 calls to zap2it, one for each tivo, or is it calling once, caching, and using the cache for the others?

**Comment by groupwhere** [comment]
Unfortunately, I do not have sufficient devices to have tested operation with more than one device.  So, this is probably the result.  I could attempt to rework this in the blind.  As you said, it is currently likely to grab the data for each device.

**Comment by jcollas** [comment]
In 0.4.0, only one call is made to zap2it, no matter how many devices you have.
