### ISSUE TITLE
Error doing job: Task exception was never retrieved

### ISSUE THREAD

**Issue by va-lemon** [groupwhere/homeassistant-tivo#8]
The below error shows up in the Home Assistant logs several times a minute. It seems to have stopped appearing about five minutes after I started Home Assistant. The TiVo component seems to be working like it's supposed to though.

2018-11-29 15:59:25 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/helpers/entity.py", line 239, in async_update_ha_state
    attr = self.state_attributes or {}
  File "/usr/src/app/homeassistant/components/media_player/__init__.py", line 787, in state_attributes
    in ATTR_TO_PROPERTY if getattr(self, attr) is not None
  File "/usr/src/app/homeassistant/components/media_player/__init__.py", line 787, in <dictcomp>
    in ATTR_TO_PROPERTY if getattr(self, attr) is not None
  File "/config/custom_components/media_player/tivo.py", line 350, in media_content_id
    return self._current["status"]
KeyError: 'status'

**Comment by jcollas** [comment]
Fixed in 0.3.0

**Comment by va-lemon** [comment]
I have not seen this error since updating to version 3.0. This issue could be closed.

**Comment by va-lemon** [comment]
I did see one more instance of this error but I believe it's a different cause from the original. Looks like an error during login to the zap2it service.

```
2019-07-03 06:48:41 ERROR (MainThread) [homeassistant.core] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/tivo/media_player.py", line 126, in zap2it_update
    tivo.zap_update()
  File "/config/custom_components/tivo/media_player.py", line 602, in zap_update
    self.zapget_data()
  File "/config/custom_components/tivo/media_player.py", line 633, in zapget_data
    self.zaplogin()
  File "/config/custom_components/tivo/media_player.py", line 616, in zaplogin
    res = urllib.request.urlopen(req, timeout=5)
  File "/usr/local/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/local/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/usr/local/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.7/urllib/request.py", line 1360, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/local/lib/python3.7/urllib/request.py", line 1320, in do_open
    r = h.getresponse()
  File "/usr/local/lib/python3.7/http/client.py", line 1321, in getresponse
    response.begin()
  File "/usr/local/lib/python3.7/http/client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.7/http/client.py", line 257, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.7/ssl.py", line 1052, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/lib/python3.7/ssl.py", line 911, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out
```
